before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'org.reactjs.native.example.brisbane', type: 'development', readonly: true)
    match(app_identifier: 'org.reactjs.native.example.brisbane', type: 'appstore', readonly: true)
  end

  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: './ios/brisbane.xcodeproj')
    gym(scheme: 'brisbane', project: './ios/brisbane.xcodeproj')
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "./ios/brisbane.xcodeproj")
    build_app(scheme: "brisbane")
    upload_to_app_store
  end
end

platform :android do
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
