export const SIGN_UP_SUCCESS = 'sign_up_success'
export const SIGN_IN_SUCCESS = 'sign_in_success'
export const AUTH_FAILED_ALERT = 'authentication_failed'
export const SHOW_ALERT = 'show_alert'
export const FORGOT_PASSWORD_SUCCESS = 'forgot_password_success'
export const UPDATE_USER_INFO = 'update_user_info'
